Lychee (link checker) as pre-commit hook (#31)
* Lychee as pre-commit hook

* Include jupyter notebooks

* Install Lychee binary in CI action

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -18,7 +18,6 @@ repos:
       # Run the formatter.
       - id: ruff-format
 
-
   # Markdown
   - repo: https://github.com/igorshubovych/markdownlint-cli
     rev: v0.47.0
@@ -34,7 +33,7 @@ repos:
     hooks:
       - id: nbqa-pyright
         name: nbqa-pyright
-        # 'uv run' ensures the hook sees your pyproject.toml dependencies
+        # 'uv run' ensures the hook sees pyproject.toml dependencies
         entry: uv run nbqa pyright
         language: system
         types: [jupyter]
@@ -44,3 +43,38 @@ repos:
         entry: bash -c 'rm -f **/*_pyright_ipynb.py'
         language: system
         pass_filenames: false
+
+  - repo: local
+    hooks:
+    # Check hyperlinks and external links
+    - id: lychee-link-checker
+      name: lychee-link-checker
+      verbose: true
+      language: system
+      require_serial: true
+      entry: |
+        /bin/bash -c '
+        if ! command -v lychee >/dev/null 2>&1; then
+            echo "--------------------------------------------------------"
+            echo "Warning: Lychee (link checker) not found. Skipping ... "
+            echo ""
+            echo "To enable local link checking, install Lychee:"
+            echo "  - MacOS: brew install lychee"
+            echo "  - Linux/Windows: https://github.com/lycheeverse/lychee"
+            echo "--------------------------------------------------------"
+            exit 0
+        fi
+        lychee "$@"
+        ' --
+      args:
+        - "--quiet"
+        - "--no-progress"
+        - "--exclude-path=(^|/)\\.[^/]+/"
+        - "--root-dir=."
+        - "--accept=200,403,429,503"
+        - "--exclude=http://localhost:.*"
+        - "--exclude=http://127.0.0.1:.*"
+        - "--max-retries=5"
+        - "--retry-wait-time=10"
+        - "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
+      types_or: [markdown, python, jupyter]
