Disable the workflow

diff --git a/.github/workflows/test_notebooks.yaml b/.github/workflows/test_notebooks.yaml
--- a/.github/workflows/test_notebooks.yaml
+++ b/.github/workflows/test_notebooks.yaml
@@ -19,6 +19,11 @@ jobs:
         python-version: ['3.13']
 
     steps:
+      - name: Workflow Disabled
+        run: |
+          echo "Reason: This workflow is temporarily disabled to save CI minutes"
+          exit 1  # This force-fails the step and stops the workflow
+
         # Installing ExifTool
       - name: Install system dependencies (Ubuntu)
         if: runner.os == 'Linux'
